services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
  chromadb:
    image: chromadb/chroma
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      IS_PERSISTENT: "TRUE"

  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    volumes:
      - ./config:/app/config
      - gateway_memory:/app/data
    env_file:
      - .env
    depends_on:
      - ollama
      - chromadb

  ingestion:
    build: ./ingestion
    ports:
      - "8001:8001"
    volumes:
    - ./config:/app/config
    env_file:
    - .env
    depends_on:
     - ollama
     - chromadb

volumes:
  ollama_data:
  chroma_data:
  gateway_memory:
